# Generated by Django 3.1.4 on 2020-12-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_auto_20201207_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_media',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
