# Generated by Django 3.1.4 on 2020-12-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_comment_comment_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_post',
        ),
    ]
