# Generated by Django 3.1.4 on 2020-12-08 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0004_remove_comment_parent_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
